### ISSUE TITLE
Address Array?

### ISSUE THREAD

**Issue by treschain** [deFang/MultiSend#1]
Can you give example of the array for the addresses?

Also i think we can call the approval from the contract using.
_token.approve(address(this), _value);

What do you think?

**Comment by deFang** [comment]
Hi, sorry for the late response.
You might check the following transaction
https://bscscan.com/tx/0x33d3bd2d0ba2a01eedd53d8858fa19439bd7c40600f04cc174f40c796d1880c1

the address array looks like
`[0xb2988937069b2F11D72749EB3aA43091B2b8B946, 0x87e35D4b21B17d5360A280Bd1F1A89a594Dd6Bc8, 0xC25fe9d86C89ecDc8bfE02FbcAfd27794058bDf8]`

Yes, remember to approve the contract before transfer any token. I like your suggestion.
